# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,mapping:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Taxonomic group
taxonomic_group: Collembola
# Name of species being analyzed
species_name: Entomobrya nicoleti
# Path to reference genome file in FASTA format
reference_genome_path: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Entomobrya_nicoleti/EG_EntNic_05092024_genomic.fna
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps/mapping_test
# # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path: 
# AdapterRemoval settings.
adapterremoval_settings:
  min_quality: 25
  min_length: 20
  adaptersequence1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
  adaptersequence2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
# Samtools filter settings.
filter_settings:
  flags_excluded: 3844
  flags_required: 
  min_mq: 20
# List of path to sample folders containing resequencing data.
sample_lists:
  -
    group_name: Azenta1
    sample_folder_list:
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Entomobrya_nicoleti/EntNic_FaaJ-C248
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Entomobrya_nicoleti/EntNic_HaeJ-C281
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Entomobrya_nicoleti/EntNic_STJ-C108
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Entomobrya_nicoleti/EntNic_TRJ-C35
  -
    group_name: Azenta2
    sample_folder_list:
      - /faststorage/project/EcoGenetics/people/Jesper_Bechsgaard/Azenta_test/fastq/C35
      - /faststorage/project/EcoGenetics/people/Jesper_Bechsgaard/Azenta_test/fastq/C108
      - /faststorage/project/EcoGenetics/people/Jesper_Bechsgaard/Azenta_test/fastq/C248
      - /faststorage/project/EcoGenetics/people/Jesper_Bechsgaard/Azenta_test/fastq/C281