# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,alignment,depth:workflowconfiguration
# (str). The name of the relevant project account.
account: EcoGenetics
# (str). Taxonomic group. Can be left empty.
taxonomicGroup: beetles
# (str). Name of species being analyzed.
speciesName: Apion fulvipes
# (str). Directory for intermediary files.
workingDirectoryPath: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps
# (str). Directory for final output files. (If left empty, output file will be placed within 'workingDirectoryPath').
outputDirectoryPath: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics
# (list). Sample setup. List of dictionaries listing the configuration for each sample.
sampleList:
  - 
    # (str). Name of sample group.
    groupName: 
    # (int). A lower coverage threshold for the identification of a coverage distribution peak.
    lowerCoverageThreshold: 
    # (list). List of paths to BAM files.
    bamFileList:
      - 