# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,mapping:workflowconfiguration
# The name of the relevant project account.
account: EcoGenetics
# Taxonomic group
taxonomic_group: Collembola
# Name of species being analyzed
species_name: Isotoma viridis
# Path to reference genome file in FASTA format
reference_genome_path: /faststorage/project/EcoGenetics/BACKUP/population_genetics/reference_genomes/collembola/Isotoma_viridis/EG_IsoVir_23082024_genomic.fna
# Directory for intermediary files.
working_directory_path: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps/mapping_test
# # Directory for final output files. (If left empty, output file will be placed within 'working_directory_path')
output_directory_path: 
# AdapterRemoval settings.
adapterremoval_settings:
  min_quality: 25
  min_length: 20
  adaptersequence1: AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
  adaptersequence2: AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG
# Samtools filter settings.
filter_settings:
  flags_excluded: 3844
  flags_required: 
  min_mq: 20
# List of path to sample folders containing resequencing data.
sample_lists:
  -
    group_name: Grassland
    sample_folder_list:
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_aeRoe-C310
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_BJJ-C98
      - /faststorage/project/EcoGenetics/BACKUP/population_genetics/fastq/collembola/Isotoma_viridis/IsoVir_BIJ-C211