# Tag identifying file association.
TAG: jeppebayer:EcoGenetics,population_genetics,alignment,depth:workflowconfiguration
# (str). The name of the relevant project account.
account: EcoGenetics
# (str). Taxonomic group. Can be left empty.
taxonomicGroup: beetles
# (str). Name of species being analyzed.
speciesName: Tenus fulvicornis
# (str). Directory for intermediary files.
workingDirectoryPath: /faststorage/project/EcoGenetics/people/Jeppe_Bayer/population_genetics/steps
# (str). Directory for final output files. (If left empty, output file will be placed within 'workingDirectoryPath').
outputDirectoryPath: /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics
# (list). Sample setup. List of dictionaries listing the configuration for each sample.
sampleList:
  - 
    # (str). Name of sample group.
    groupName: Grassland
    # (int). A lower coverage threshold for the identification of a coverage distribution peak.
    lowerCoverageThreshold: 100
    # (list). List of paths to BAM files.
    bamFileList:
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/beetles/Stenus_fulvicornis/grassland/SteFul_aaRJ/SteFul_aaRJ.filtered.clipOverlap.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/beetles/Stenus_fulvicornis/grassland/SteFul_aeRoe/SteFul_aeRoe.filtered.clipOverlap.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/beetles/Stenus_fulvicornis/grassland/SteFul_BIJ/SteFul_BIJ.filtered.clipOverlap.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/beetles/Stenus_fulvicornis/grassland/SteFul_DoeJ/SteFul_DoeJ.filtered.clipOverlap.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/beetles/Stenus_fulvicornis/grassland/SteFul_GSJ/SteFul_GSJ.filtered.clipOverlap.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/beetles/Stenus_fulvicornis/grassland/SteFul_JEJ/SteFul_JEJ.filtered.clipOverlap.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/beetles/Stenus_fulvicornis/grassland/SteFul_LEJ/SteFul_LEJ.filtered.clipOverlap.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/beetles/Stenus_fulvicornis/grassland/SteFul_LVJ/SteFul_LVJ.filtered.clipOverlap.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/beetles/Stenus_fulvicornis/grassland/SteFul_MSJ/SteFul_MSJ.filtered.clipOverlap.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/beetles/Stenus_fulvicornis/grassland/SteFul_SKJ/SteFul_SKJ.filtered.clipOverlap.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/beetles/Stenus_fulvicornis/grassland/SteFul_SKS/SteFul_SKS.filtered.clipOverlap.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/beetles/Stenus_fulvicornis/grassland/SteFul_SUJ/SteFul_SUJ.filtered.clipOverlap.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/beetles/Stenus_fulvicornis/grassland/SteFul_TRJ/SteFul_TRJ.filtered.clipOverlap.bam
      - /faststorage/project/EcoGenetics/general_workflow_outputs/population_genetics/alignments/beetles/Stenus_fulvicornis/grassland/SteFul_ULJ/SteFul_ULJ.filtered.clipOverlap.bam